export const NUMBER_TO_NUMBER_NAME: {
  [key: number]: string;
} =
{
  0: 'zero',
  1: 'one',
  2: 'two',
  3: 'three',
  4: 'four',
  5: 'five',
  6: 'six',
  7: 'seven',
  8: 'eight',
  9: 'nine',
  10: 'ten',
  11: 'eleven',
  12: 'twelve',
  13: 'thirteen',
  14: 'fourteen',
  15: 'fifteen',
  16: 'sixteen',
  17: 'seventeen',
  18: 'eighteen',
  19: 'nineteen',
  20: 'twenty',
  21: 'twenty-one',
  22: 'twenty-two',
  23: 'twenty-three',
  24: 'twenty-four',
  25: 'twenty-five',
  26: 'twenty-six',
}
export const NON_LETTER_CHAR_TO_NAME: {
  [key: string]: string;
} = {
  '~': 'tilde',
  '`': 'backtick',
  '!': 'exclamation',
  '@': 'at',
  '#': 'hash',
  '$': 'dollar',
  '%': 'percent',
  '^': 'caret',
  '&': 'ampersand',
  '*': 'asterisk',
  '(': 'open-parenthesis',
  ')': 'close-parenthesis',
  '-': 'dash',
  '_': 'underscore',
  '=': 'equal',
  '+': 'plus',
  '[': 'open-bracket',
  ']': 'close-bracket',

  '{': 'open-curly-bracket',
  '}': 'close-curly-bracket',
  '\\': 'backslash',
  '|': 'pipe',
  ';': 'semicolon',
  ':': 'colon',
  '\'': 'single-quote',
  '"': 'double-quote',
  ',': 'comma',
  '<': 'less-than',
  '.': 'period',
  '>': 'greater-than',
  '/': 'slash',
  '?': 'question',

}

export const NON_LETTERS = Object.keys(NON_LETTER_CHAR_TO_NAME);
